version: "2"

services:
  test:
    container_name: ${BUILD_TAG}tuleap_runtests_test-e2e
    image: tuleap-run-e2e-tests-v2
    build:
      context: ./tests/e2e/DockerImage
    command: /tuleap/tests/e2e/full/run.sh
    volumes:
      - .:/tuleap
      - ${TEST_RESULT_OUTPUT}:/output
    networks:
      - tuleap
      - external-connectivity

  tuleap:
    container_name: ${BUILD_TAG}tuleap_runtests_backend-web-e2e
    image: enalean/tuleap-test-rest:c6-php56-mysql56
    command: /usr/share/tuleap/tests/e2e/full/tuleap/setup.sh
    volumes:
      - .:/usr/share/tuleap
    networks:
      - tuleap

networks:
  tuleap:
    internal: true
  external-connectivity: