# This compose file is provided for test purpose as:
# * the database is part of this compose file and that's not suitable for production
# * password are either hardcoded to dumb value or not existent (redis)
#
# You should have a .env file with 2 variables defined:
# TULEAP_FQDN
# MYSQL_ROOT_PASSWORD
# See https://docs.docker.com/compose/environment-variables/

version: "2"

services:
  web:
    image: tuleap/tuleap-community-edition:dev
    hostname: ${TULEAP_FQDN}
    volumes:
      # For Tuleap devs, un-comment if you want to test stuff with your own code base
      # - ../../../:/usr/share/tuleap:ro,cached
      - tuleap-data:/data
    depends_on:
      - db
      - redis
      - mailhog
    environment:
      - TULEAP_FQDN=${TULEAP_FQDN}
      - DB_HOST=db
      - DB_ADMIN_USER=root
      - DB_ADMIN_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TULEAP_FPM_SESSION_MODE=redis
      - TULEAP_REDIS_SERVER=redis
      #- TULEAP_REDIS_PASSWORD=${REDIS_PASSWORD}
      - TULEAP_EMAIL_RELAYHOST=mailhog:1025

  # This is for test purpose only. It's not advised to run a production database as a docker container
  db:
    image: mysql:5.7
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--sql-mode=NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db57-data:/var/lib/mysql

  # This is for test purpose only. It's not advised to run a production database as a docker container
  redis:
    image: redis:6
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  # This is for test purpose only. Mailhog is there to capture email traffic
  mailhog:
    image: mailhog/mailhog

volumes:
  tuleap-data:
  db57-data:
  redis-data:
